config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "splash#index"
  get 'splash/index'
  get 'transaction/index/:id', to: 'transaction#index', as: 'transaction_index_path'
  post 'transaction/create'
  get 'transaction/new/:id', to: 'transaction#new', as: 'transaction_new_path'
  get 'catagory/index'
  get 'catagory/new'
  post 'catagory/create'
  
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # return unless user.present?

    can :manage, Record, author_id: user.id
    can :manage, Catagory, author_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/catagory.rb
class Catagory < ApplicationRecord
  belongs_to :author, class_name: 'User'

  has_many :catagory_records, dependent: :destroy

  # validations
  validates :name, presence: true
  validates :icon, presence: true
  validates :name, length: { maximum: 100 }
  validates_associated :catagory_records
end

app/models/catagory_record.rb
class CatagoryRecord < ApplicationRecord
  belongs_to :record
  belongs_to :catagory
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :author, class_name: 'User'

  has_many :catagory_records, dependent: :destroy

  # validations
  validates :name, presence: true
  validates :amount, presence: true
  validates :amount, numericality: true
  validates :amount, numericality: { greater_than: 0 }
  validates :name, length: { maximum: 100 }
  validates_associated :catagory_records
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :records, foreign_key: 'author_id'
  has_many :catagories, foreign_key: 'author_id'

  # validations
  validates :name, presence: true
  validates :name, length: { maximum: 50 }
  validates_associated :records
  validates_associated :catagories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  def after_sign_out_path_for(_resource)
    splash_index_path
  end

  def after_sign_in_path_for(_resource)
    catagory_index_path
  end
end

app/controllers/catagory_controller.rb
class CatagoryController < ApplicationController
  before_action :authenticate_user!
  def index
    @catagories = current_user.catagories.includes(:catagory_records)
    @totals = @catagories.map do |catagory|
      catagory.catagory_records.reduce(0) { |sum, num| sum + num.record.amount }
    end
  end

  def new
    @new_catagory = Catagory.new
  end

  def create
    @new_catagory = Catagory.new(catagory_params)
    @new_catagory.author = current_user
    if @new_catagory.save
      redirect_to '/catagory/index'
    else
      redirect_to :new
    end
  end

  private

  def catagory_params
    params.require(:new_catagory).permit(:name, :icon)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/controllers/transaction_controller.rb
class TransactionController < ApplicationController
  before_action :authenticate_user!
  def index
    @records = current_user.records.select { |record| record.catagory_records[0].catagory.id == params[:id].to_i }
    @total = @records.reduce(0) { |sum, num| sum + num.amount }

    @catagory_id = params[:id]
    @catagory = Catagory.find(@catagory_id)
  end

  def create
    @new_record = Record.new(name: transaction_params[:name], amount: transaction_params[:amount])
    @new_record.author = current_user
    @new_record.save
    @selected_catagory = Catagory.find(transaction_params[:catagory])
    @new_catagory_record = CatagoryRecord.new(record: @new_record, catagory: @selected_catagory)
    @new_catagory_record.save
    if @new_catagory_record.save && @new_record.save
      redirect_to "/transaction/index/#{transaction_params[:catagory]}"
    else
      render :new
    end
  end

  def new
    @new_record = Record.new
    @catagories = current_user.catagories.map { |catagory| [catagory.name, catagory.id] }
    @catagory_id = params[:id]
    @catagory_page_path = transaction_index_path_url(id: params[:id])
  end

  private

  def transaction_params
    params.require(:new_record).permit(:name, :amount, :catagory_id, :catagory)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catagory_helper.rb
module CatagoryHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/views/catagory/create.html.erb
<h1>Catagory#create</h1>
<p>Find me in app/views/catagory/create.html.erb</p>

app/views/catagory/index.html.erb
<%= render partial: '/partials/navbar',locals: {p: catagory_index_path, title: 'Catagories'} %>
<div class="container bg-light">
<% if @catagories.length == 0 %>
<h2 class="text-center mt-5">You have no categories registered</h2>
<% end %>
<% @catagories.each_with_index do |catagory,idx| %>
<a href=<%= transaction_index_path_url(id: catagory.id)%> style="text-decoration: none;color: inherit;">
<div  class='d-flex justify-content-between p-2 my-3 border bg-white'>
    <div>
    <img 
    class="icon" 
    style="width:50px"
    src=<%= catagory.icon %>
    alt="face" />
    </div>
    <div class="flex-grow-1 px-1">
        <h2><%= catagory.name%></h2>
        <small class="text-muted"><%= catagory.created_at.strftime("%d  %B %Y at %I:%M %p") %></small>
    </div>
    <div>
        <span>
            <%= @totals[idx] %>$  
        </span>
    </div>
</div>
<% end %>
</a>
<div class="d-flex justify-content-center p-5">
<%= button_to "create catagory", catagory_new_path, method: :get,class:"btn btn-success btn-lg" %>
</div>
</div>

app/views/catagory/new.html.erb
<%= render partial: '/partials/navbar',locals: {p: catagory_index_path, title: 'Catagories'} %>
<div class="container p-3 d-flex flex-column align-items-stretch">
<%= form_with model: @new_catagory, url: catagory_create_path, method: :post, local: true, scope: :new_catagory do |f| %>
    <div class="form-group">
    <%= f.label :Name %><br>
    <%= f.text_field :name,class:"form-control" %>
    </div>

    <div class="form-group">
    <%= f.label :Icon %><br>
    <%= f.text_field :icon,class:"form-control"%>
    </div>

    <%= f.submit "Save",class:"btn btn-primary" %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
  </head>

  <body>
 
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/partials/_category.html.erb
<div  class='d-flex justify-content-between p-2 py-5 my-3 border bg-white'>
    <div>
    <img 
    class="icon" 
    style="width:50px"
    src=<%= catagory.icon %>
    alt="face" />
    </div>
    <div class="flex-grow-1 px-2">
        <h2><%= catagory.name%></h2>
        <span><%= catagory.created_at.strftime("%d  %B %Y at %I:%M %p") %></span>
    </div>
    <div>
        <span>
            <%= total %> $  
        </span>
    </div>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-light bg-primary justify-content-between p-2">
  <a class="navbar-brand" href=<%=p%>>
  <img  src=<%= image_path("arrow-left.svg") %> style="width:50px;" class="rounded-7"/>
  </a>
  <span class='h1 text-white'><%= title%></span>
  <%= button_to "Logout", destroy_user_session_path, method: :delete,class:"btn btn-light" %>
</nav>

app/views/splash/index.html.erb
<div class="container-fluid text-center">
  <div class="position-absolute top-50 start-50 translate-middle w-50">
    <h1 >Budget App</h1>

    <div class="">
      <% if user_signed_in? %>
        <p>Welcome, <%= current_user.name %></p>
        <em>You are signed in!</em>
        <%= button_to 'Go to categories', catagory_index_path,  method: :get,  class: 'btn btn-primary  w-75 mt-5' %>
        <%= button_to 'Log out', destroy_user_session_path,  method: :delete,  class: 'btn btn-primary w-75 mt-2' %>
      <% else %>
        <%= link_to  'Log in', user_session_path, class: 'btn btn-primary  w-75 mt-5' %>
        <%= button_to  'Sign Up', new_user_registration_path, method: :get, class: 'btn signup-btn w-75 mt-3' %>
      <% end %>
    </div>
  </div>
</div>

app/views/transaction/create.html.erb
<h1>Transaction#create</h1>
<p>Find me in app/views/transaction/create.html.erb</p>

app/views/transaction/index.html.erb
<%= render partial: '/partials/navbar',locals: {p: catagory_index_path, title: 'Transactions'} %>

<div class="container bg-light">
<%= render partial: '/partials/category',locals: {catagory: @catagory, total:@total} %>
<% if @records.length == 0 %>
 <h2 class="text-center mt-5">You have no transactions associated with this category</h2>
<% end %>
<% @records.each do |record| %>
<div  class='d-flex flex-column justify-content-start p-2 my-3 border bg-white'>
    <div class="flex-grow-1 px-2">
        <h2><%= record.name%></h2>
        
    </div>
    <div class="d-flex justify-content-between">
        <span>Amount</span>
        <span>
            <%= record.amount %> $  
        </span>
    </div>
    <div>
    <span><%= record.created_at.strftime("%d  %B %Y at %I:%M %p")  %></span>
    </div>
</div>
<% end %>
<div class="d-flex justify-content-center p-5">
<%= button_to "Create transaction", transaction_new_path_url(id: @catagory_id), method: :get,class:"btn btn-success btn-lg" %>
</div>
</div>

app/views/transaction/new.html.erb
<%= render partial: '/partials/navbar',locals: {p: @catagory_page_path, title: 'Transactions'} %>
<div class="container p-3 d-flex flex-column align-items-stretch">
<h1 class="text-center mb-5">Create new transaction</h1>
<%= form_with model: @new_record, url: transaction_create_path,class:"align-self-strech", method: :post, local: true, scope: :new_record do |f| %>
    <div class="form-group">
    <%= f.label :Name %><br>
    <%= f.text_field :name,class:"form-control" %>
    </div>

    <div class="form-group">
    <%= f.label :Amount %><br>
    <%= f.number_field  :amount,class:"form-control" %>
    </div>
    <div class="form-group">
        <%= f.select :catagory, @catagories,class:"form-control" %>
    </div>
    <div class="form-group">
        <%= f.hidden_field :catagory_id, value: @catagory_id %>
    </div>

    <%= f.submit "Save",class:"btn btn-primary" %>
<% end %>
</div>